server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: user1
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

